project:
  type: website
  title: The Missing Course
  preview:
    port: 4321
    watch-inputs: true
  resources:
    - "assets/**/*"

language: 
  search-text-placeholder: Search

website:
  navbar: false
  bread-crumbs: true
  page-navigation: true
  sidebar:
    style: docked
    # background: "#f8f8f8"
    border: true
    logo-alt: "The Missing Course for Cognitive Sciences and Humanities"
    title: The Missing Course
    align: center
    pinned: true
    search: true
    collapse-level: 1
    footer: |
      <p style='font-size: .75rem' class="text-secondary fst-italic">&copy; 2025</p>
    contents:
      - text: Home
        file: index.qmd
      - file: pages/1-syllabus.qmd
      - file: pages/2-schedule.qmd
      - auto: lectures/
      - file: pages/3-resources.qmd
      - text: FAQ
        file: pages/4-faq.qmd
      - file: pages/5-about.qmd


format:
  html:
    theme:
      light:
        - brand
        - assets/css/custom.scss
    respect-user-color-scheme: true
    email-obfuscation: javascript
    toc: false
    toc-location: right
    toc-title: "Contents"
    link-external-icon: true
    link-external-newwindow: true
    grid:
      sidebar-width: 300px